### ISSUE TITLE
user does not have access to prisma.public

### ISSUE THREAD

**Issue by mattruddy** [wangel13/prisma-next-auth-graphql-starter#52]
I keep getting an error when ever starting up the application that the user doesnt have access to the database. Any idea what this could be?

`Authentication failed against database server at 'localhost', the provided database credentials for 'johndoe' are not valid.`

**Comment by wangel13** [comment]
Hello @mattruddy ! I plan to update to new Prisma this week. And then i check your issue in new version. Stay tuned :D

**Comment by nrgapple** [comment]
@wangel13 awesome news! This is a really great template. Its really the only of its kind. 

If you have time can you add a user profile query? I'm having trouble getting the session for a user and the rest of their profile on a query.

Think if there was a `Profile` table. And one of the queries was to get the signed in user's Profile. (You don't actually have to make a Profile table but maybe a query where you use the user session to get something. Like maybe itself. haha



Thanks again

**Comment by nrgapple** [comment]
Would  `graphql/context` `createContext` be something like this to pass the session into the resolvers?
```ts
export const createContext = async ({ res, req }): Promise<Context> => {
    const session = await getSession({ req });
    return {prisma, res, req, session };
}
```

I'm guessing we would have to extend the Context interface too since session is not a part of it

**Comment by nrgapple** [comment]
https://github.com/graphql-nexus/nexus-plugin-prisma/issues/1039#issuecomment-918237225

Ok I get it now. so you use next-auth api to get a session and then use next-auth/client in `isAuthenticated` to set the user's permissions in that `shield` package you are using. So in its current state would that mean the user would have full crud access to all the users? Like right now an authed user could just query for all users' data

**Comment by wangel13** [comment]
You can use [shield](https://github.com/maticzav/graphql-shield) for some checks like `isAuthenticated`, `isAuthor`, `isAdmin` or etc...  

> user would have full crud access to all the users

in example query - yes, but you can write your own rules

**Comment by nrgapple** [comment]
ahh now I get it. I should have read the docs for [`graphql-shield`](https://graphql-shield.vercel.app/docs)

**Comment by wangel13** [comment]
```javascript
const isAuthenticated = rule({ cache: 'contextual' })(async (parent, args, ctx, info) => {
  return ctx.user !== null
})

const isAdmin = rule({ cache: 'contextual' })(async (parent, args, ctx, info) => {
  return ctx.user.role === 'admin'
})

const isEditor = rule({ cache: 'contextual' })(async (parent, args, ctx, info) => {
  return ctx.user.role === 'editor'
})

// Permissions

const permissions = shield({
  Query: {
    frontPage: not(isAuthenticated),
    fruits: and(isAuthenticated, or(isAdmin, isEditor)),
    customers: and(isAuthenticated, isAdmin),
  },
  Mutation: {
    addFruitToBasket: isAuthenticated,
  },
  Fruit: isAuthenticated,
  Customer: isAdmin,
})
```

https://graphql-shield.vercel.app/docs#example

**Comment by nrgapple** [comment]
Awesome I guess the only question still is how do I get a reference to the signed in user in the resolver?

```ts
export const Queries = extendType({
  type: 'Query',
  definition: (t) => {
    t.field('example', {
      type: 'Example',
      resolve: async (_parent, _args, _ctx) => {
        return {
          message: 'Hello there!',
        }
      },
    })
  },
})
```

**Comment by wangel13** [comment]
Like this:

```javascript
export const Queries = extendType({
  type: 'Query',
  definition: (t) => {
    t.field('example', {
      type: 'Example',
      resolve: async (_parent, _args, _ctx) => {
        const session = await getSession({ req: _ctx.req })
        console.log(session)
        return {
          message: 'Hello there!',
        }
      },
    })
  },
})
```

**Comment by wangel13** [comment]
and don't forget, you have `prisma` in `ctx` so you can query in rules and queries :D

**Comment by nrgapple** [comment]
Thanks this helps a lot

**Comment by wangel13** [comment]
Feel free to ask ;)

**Comment by nrgapple** [comment]
```ts
export const Queries = extendType({
    type: 'Query',
    definition: (t) => {
      t.field('example', {
        type: 'Example',
        resolve: async (_parent, _args, {req, prisma}) => {
            const session = await getSession({ req: _ctx.req })
            return await prisma.user.findFirst()
                .where ({
                    email: session?.user?.email
                })
        },
      })
    },
  })
```

so something like that

**Comment by wangel13** [comment]
@mattruddy Check new version plz..

**Comment by deadcoder0904** [comment]
hey @wangel13 this is really helpful. found this while searching on [sourcegraph](https://sourcegraph.com).

i've copied your code but i am unable to access `getSession`. it always returns `null`. the only thing different is i'm using next-auth v4. this is my repo (`prisma` branch) → https://github.com/deadcoder0904/twitter-api-v2-3-legged-login-using-next-connect/tree/prisma

can you tell me what i'm doing wrong? struggling to `getSession` so i can query. i always get `Not Authorized` when i put this inside http://localhost:3000/api:

```graphql
# Write your query or mutation here
{
  currentUser(id: "ckv226a840006k9v5ua3xvgsk") {
    id
    name
    username
    email
  }
}
```

despite my code looks similar to yours.

**Comment by wangel13** [comment]
Hello! I think this problem connected with https://github.com/maticzav/graphql-middleware/issues/433
Downgrade graphql-shield or wait for new version ;)
