### ISSUE TITLE
Graphql sandbox unstable connection

### ISSUE THREAD

**Issue by nrgapple** [wangel13/prisma-next-auth-graphql-starter#54]
I was wondering if you knew if there is a limitation with the graphql sandbox at `/api/graphql` using nextjs. 

When I connect to the sandbox sometimes it will be able to connect and most of the time it will just not connect.

I haven't been able to find anything online.

**Comment by wangel13** [comment]
I don't know because i just upgraded project to new graphql playground. But you can change new playground to old one(it's works locally). [apollo docs](https://www.apollographql.com/docs/apollo-server/testing/build-run-queries/#graphql-playground)

**Comment by wangel13** [comment]
@nrgapple You resolved this issue?
