### ISSUE TITLE
Passing getSession token in Graphql Playground

### ISSUE THREAD

**Issue by rajatkulkarni95** [wangel13/prisma-next-auth-graphql-starter#55]
How would one pass the session token in the Apollo Playground? The one that `isAuthenticated` invokes?
Tried picking the `next-auth-session-token` value and passing it in headers for `Authorization` but that doesn't solve it

**Comment by wangel13** [comment]
Hello @rajatkulkarni95. I just released [v3.1.3](https://github.com/wangel13/prisma-next-auth-graphql-starter/commit/c7d8ec4dacdf59e1f112d42db0d423b086d8e707) that solves auth problem in apollo studio. Try to upgrade. Also you need to turn on `Include cookies` option in the studio.

![Explorer-Sandbox-Studio](https://user-images.githubusercontent.com/1074859/166924846-e9023c8b-ce43-4a59-b7f2-26e4d2a644c9.png)

**Comment by rajatkulkarni95** [comment]
Awesome! Worked, thanks a bunch

**Comment by wamir79** [comment]
@rajatkulkarni95 @wangel13 can you provide detailed instruction how to set the Authorization ? 
Thanks!!

**Comment by wangel13** [comment]
@wamir79 Here blog post about it - https://taras.one/blog/apollo-graphql-studio-next-auth

**Comment by wamir79** [comment]
Thanks @wangel13!, just forgot to clear cookies after cookiesPolicy update :)
